#!/usr/bin/env ash

set -e

main() {
  mkdir -p "$REPODEST" /home/builder/.abuild
  abuild-apk update
  abuild-keygen -a -i

  sudo chown -R builder:abuild /home/builder/package
  sudo chown -R builder:abuild $REPODEST

  exec abuild "$@"
}

main "$@"
